---
Example:
  nick: ebot
  leaves:
  - Administrator
  - Tf2
  - Lunch
  rejoin: true
  channels:
  - "#TeamFuncom"
  server: irc.gamesurge.net
  throttle: true
  throttle_rate: 1
  throttle_threshold: 4
